"""add_authorized_roles

Revision ID: 0b9502fb03b6
Revises: f7c491a3be6e
Create Date: 2025-12-14 17:29:10.320049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b9502fb03b6'
down_revision: Union[str, None] = 'f7c491a3be6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    CREATE TABLE authorized_roles (
        id BIGSERIAL PRIMARY KEY,
        guild_id BIGINT NOT NULL,
        role_id VARCHAR NOT NULL,
        permission_level permissionlevel DEFAULT 'USER',
        created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
        created_by BIGINT,
        CONSTRAINT fk_guild FOREIGN KEY (guild_id) REFERENCES guilds(id)
    );
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('authorized_roles')
    # ### end Alembic commands ###
