"""add guild settings

Revision ID: 64d812d46e18
Revises: 1268043d8849
Create Date: 2025-11-21 02:09:09.563921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64d812d46e18'
down_revision: Union[str, None] = '1268043d8849'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shards',
    sa.Column('shard_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('latency', sa.BigInteger(), nullable=True),
    sa.Column('guild_count', sa.BigInteger(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('shard_id')
    )
    op.create_table('guild_settings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('settings_json', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guild_settings')
    op.drop_table('shards')
    # ### end Alembic commands ###
